version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - mynetwork

  auth-service:
    container_name: auth-service
    build: ./authentication
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8081
    networks:
      - mynetwork

  movie-service:
    container_name: movie-service
    build: ./movies
    ports:
      - "5000:8000"
    environment:
      - DJANGO_ENV=production
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    networks:
      - mynetwork

  notification-service:
    container_name: notification-service
    build: ./notification
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - mynetwork

  gateway-service:
    container_name: gateway-service
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - AUTH_SERVICE_URL=http://auth-service:8081
      - MOVIE_SERVICE_URL=http://movie-service:8000
      - NOTIFICATION_SERVICE_URL=http://notification-service:3003
    depends_on:
      - auth-service
      - movie-service
      - notification-service
    networks:
      - mynetwork

  web-client:
    container_name: web-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - gateway-service
    networks:
      - mynetwork
    restart: unless-stopped

networks:
  mynetwork:
    driver: bridge
