version: "3.9"

services:
  auth-service:
    build: ./authentication
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8081
    networks:
      - mynetwork

  movie-service:
    build: ./movies
    ports:
      - "5000:8000"
    environment:
      - DJANGO_ENV=production
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  notification-service:
    build: ./notification
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    networks:
      - mynetwork

  gateway-service:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - AUTH_SERVICE_URL=http://auth-service:8081/auth
      - MOVIE_SERVICE_URL=http://movie-service:8000
      - NOTIFICATION_SERVICE_URL=http://notification-service:3003
    depends_on:
      - auth-service
      - movie-service
    networks:
      - mynetwork

  web-client:
    build: ./client
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge