springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

jwt:
  private:
    key: "classpath:app.key"
  public:
    key: "classpath:app.pub"

account:
  cors:
    allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS:*}
    
openapi:
  server-url: ${OPENAPI_SERVER_URL:http://localhost:8080}

server:
  forward-headers-strategy: native

services:
  auth:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}
  soap:
    url: ${SOAP_SERVICE_URL:http://localhost:5000}